모델 분리하기
Team-B1ND/dodamdodam-android-v4 pull request #110
Opened 2023-04-01 02:58 UTC by wsi1212

## 개요
model이 독립적이지 못함→ 유지보수성 낮음

## 작업사항
* 모델을 독립적으로 분리했습니다.

2023-04-01 06:45 UTC, snack655 reviewed
수정할 부분이 많이 보이네요.
그리고 215개의 파일 변경에 비해서  PR에 작성된 글도 자세하지 않네요.
Param 객체의 개발 이유부터 entity의 처리 등 설명이 적혀있지 않아요.
이유 없는 개발은 위험합니다. 왜 자신이 이 코드를 짰는지 제대로 생각한 후에 자세하게 적어주세요.

2023-04-01 06:45 UTC, snack655 commented on data/src/main/java/kr/hs/dgsw/smartschool/data/datasource/MealDataSource.kt
> +    suspend fun getMeal(date: String): MealResponse {
여기 급식 쪽에 리뷰를 적지만 DataSource, Repository 전부 포함되는 내용입니다.
 * Repository에서 MealResponse를 toModel()을 통해서 Response를 model로 변경하고 있는데, 왜 Datasource에서 entity를 toModel()이라는 이름의 함수로 Response로 형 변환을 시키죠? 함수 이름과 역할이 맞지 않습니다.
 * 애초에 entity를 왜 Response type으로 변경시키죠? entity는 local의 객체이고 response는 remote의 객체입니다.
 - response -> model
 - entity -> model
이게 맞는 구조라고 생각합니다.

제가 생각하는 해결은
```kotlin
suspend fun getMeal(data: String): Meal {
    ...
   return .. ?: Meal(..)
}
```
현재와 같은 entity -> response -> model은
유지보수성을 저하한다고 생각합니다.

2023-04-01 06:45 UTC, snack655 commented on domain/src/main/java/kr/hs/dgsw/smartschool/domain/param/song/SongParam.kt
> +data class SongParam(
왜 Param 객체를 따로 개발했는지 모르겠네요..
그리고 Param 객체가 Presentation, Data에서 모두 사용되는데 당연히 유지보수성을 낮추게 됩니다.

심지어 모든 기능에 Param 객체가 있는 것도 아닙니다.
급식을 보면 기존의 방식과 같은 방식으로 하고 있죠.
하나의 방식으로 통일 시키는 것이 좋다고 생각하고
기존의 Usecase에서 data class를 가지는 방식이 독립적으로 유지보수성을 높일 수 있다고 생각합니다.

2023-04-01 06:48 UTC, snack655 reviewed
KtLint 검사는 한 것이 맞나요?

2023-04-01 09:18 UTC, kdh1123 commented on data/src/main/java/kr/hs/dgsw/smartschool/data/mapper/OutMapper.kt
> +fun OutParam.toRequest(): OutRequest = OutRequest(
제 생각에 mapper에서는
 
response -> model
model -> entity
entity -> model

위의 동작만 관리하고, 

Request와 Param은 mapper에서  관여하지 않고
Param은 usecase 안 data class로 놔두고,
Request는 remote 에서 파라미터로 Request 객체를 받아서 service(api)로 넘겨주는 게 좋다고 생각합니다.

datasource에서 데이터를 가공하는 동작이 존재할 수 있고
 Param 객체 형태로 데이터를 전달하면 오히려 로직이 복잡해지고 유지보수성이 떨어지는 결과가 생긴다고 보네요.

2023-04-01 09:18 UTC, kdh1123 commented on domain/src/main/java/kr/hs/dgsw/smartschool/domain/repository/StudyRoomRepository.kt
Param이랑 Request 조금 더 고민해보시기 바랍니다

2023-04-01 09:20 UTC, kdh1123 commented
> 수정할 부분이 많이 보이네요. 그리고 215개의 파일 변경에 비해서 PR에 작성된 글도 자세하지 않네요. Param 객체의 개발 이유부터 entity의 처리 등 설명이 적혀있지 않아요. 이유 없는 개발은 위험합니다. 왜 자신이 이 코드를 짰는지 제대로 생각한 후에 자세하게 적어주세요.
> 
> PR에 projects, development도 등록되지 않았습니다.

위에서 말한 것처럼 PR 자세히 작성하는 것도 잊지 마세요

2023-04-05 11:20 UTC, wsi1212 commented on data/src/main/java/kr/hs/dgsw/smartschool/data/datasource/MealDataSource.kt
> +    suspend fun getMeal(date: String): MealResponse {
Mapper 에서는 Model -> Entity, Entity -> Model, Response -> Model 작업만 하도록 수정했습니다!

2023-04-05 11:21 UTC, wsi1212 commented on domain/src/main/java/kr/hs/dgsw/smartschool/domain/param/song/SongParam.kt
> +data class SongParam(
Param을 Usecase가 가지도록 수정 했습니다.

2023-04-05 11:22 UTC, wsi1212 commented on data/src/main/java/kr/hs/dgsw/smartschool/data/mapper/OutMapper.kt
> +fun OutParam.toRequest(): OutRequest = OutRequest(
Mapper 에서는 위 세가지만 하도록 수정하였고 request도 datasource 까지는 Usecase.Param으로 전달 후 datasource에서 request 형으로 변환 후 remote로 전달되게 수정했습니다.

2023-04-10 23:17 UTC, SeokgyuYun commented
병합 오류 해결해주세요

2023-04-10 23:29 UTC, SeokgyuYun reviewed
코드 여러번 수정하느라 수고하셨습니다.
병합 오류만 해결해주세요.

2023-04-10 23:30 UTC, SeokgyuYun requested changes
코드 여러번 수정하느라 수고하셨습니다.
병합 오류만 해결해주세요.

2023-04-10 23:37 UTC, SeokgyuYun approved these changes

2023-04-12 07:47 UTC, merged